let games = [
  { id: '1', title: 'The Last of Us Part II', price: 60, description: 'lorem ipsum', platform: ['PS4'] },
  { id: '2', title: 'Ghost of Tsushima', price: 70, description: 'lorem ipsum', platform: ['PS4'] },
  { id: '3', title: 'Death Stranding', price: 80, description: 'lorem ipsum', platform: ['PS4', 'PC'] },
  { id: '4', title: 'God of War', price: 50, description: 'lorem ipsum', platform: ['PS4'] },
  { id: '5', title: 'Red Dead Redemption 2', price: 60, description: 'lorem ipsum', platform: ['PS4', 'Xbox'] },
  { id: '6', title: 'Resident Evil Village', price: 70, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '7', title: 'Horizon Forbidden West', price: 80, description: 'lorem ipsum', platform: ['PS4', 'PS5'] },
  { id: '8', title: 'Call of Duty: Black Ops Cold War', price: 60, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '9', title: 'Cyberpunk 2077', price: 70, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '10', title: 'Assassin\'s Creed Valhalla', price: 80, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '11', title: 'Spider-Man: Miles Morales', price: 50, description: 'lorem ipsum', platform: ['PS4', 'PS5'] },
  { id: '12', title: 'Demon\'s Souls', price: 60, description: 'lorem ipsum', platform: ['PS5'] },
  { id: '13', title: 'Rainbow Six Siege', price: 50, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '14', title: 'Forza Horizon 4', price: 70, description: 'lorem ipsum', platform: ['Xbox'] },
  { id: '15', title: 'Sea of Thieves', price: 60, description: 'lorem ipsum', platform: ['Xbox', 'PC'] },
  { id: '16', title: 'Overcooked 2', price: 20, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '17', title: 'Apex Legends', price: 0, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '18', title: 'Fortnite', price: 0, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '19', title: 'Rocket League', price: 20, description: 'lorem ipsum', platform: ['PS4', 'Xbox', 'PC'] },
  { id: '20', title: 'Among Us', price: 5, description: 'lorem ipsum', platform: ['PC'] },
]

let authors = [
  { id: '1', name: 'IGN', verified: true },
  { id: '2', name: 'GameSpot', verified: true },
  { id: '3', name: 'Polygon', verified: true },
  { id: '4', name: 'Kotaku', verified: true },
  { id: '5', name: 'Destructoid', verified: true },
  { id: '6', name: 'Eurogamer', verified: true },
  { id: '7', name: 'Killer Guides', verified: false },
]

let reviews = [
  { id: '1', rating: 10, description: 'Awesome gameplay!', author_id: '1', game_id: '1' },
  { id: '2', rating: 10, description: 'Best game ever!', author_id: '2', game_id: '1' },
  { id: '3', rating: 5, description: 'Good but not great.', author_id: '3', game_id: '2' },
  { id: '4', rating: 5, description: 'Not my cup of tea.', author_id: '4', game_id: '3' },
  { id: '5', rating: 8, description: 'Great story!', author_id: '5', game_id: '5' },
  { id: '6', rating: 5, description: 'Too short.', author_id: '1', game_id: '4' },
  { id: '7', rating: 10, description: 'Best multiplayer game!', author_id: '2', game_id: '4' },
  { id: '8', rating: 8, description: 'Good graphics.', author_id: '3', game_id: '5' },
  { id: '9', rating: 5, description: 'Not bad.', author_id: '4', game_id: '6' },
  { id: '10', rating: 10, description: 'Best game of the year!', author_id: '5', game_id: '7' },
  { id: '11', rating: 9, description: 'Good controls.', author_id: '1', game_id: '8' },
  { id: '12', rating: 9, description: 'Good game.', author_id: '2', game_id: '9' },
  { id: '13', rating: 8, description: 'Good story.', author_id: '3', game_id: '10' },
  { id: '14', rating: 5, description: 'Good game.', author_id: '4', game_id: '11' },
  { id: '15', rating: 10, description: 'Best game ever!', author_id: '5', game_id: '12' },
  { id: '16', rating: 4, description: 'Not great.', author_id: '6', game_id: '13' },
  { id: '17', rating: 5, description: 'Good game.', author_id: '7', game_id: '14' },
  { id: '18', rating: 8, description: 'Good gameplay.', author_id: '1', game_id: '15' },
  { id: '19', rating: 9, description: 'Good story.', author_id: '2', game_id: '16' },
  { id: '20', rating: 10, description: 'Best game of the year!', author_id: '3', game_id: '17' },
  { id: '21', rating: 5, description: 'Good controls.', author_id: '4', game_id: '18' },
  { id: '22', rating: 8, description: 'Good graphics.', author_id: '5', game_id: '19' },
  { id: '23', rating: 10, description: 'Best multiplayer game!', author_id: '6', game_id: '20' },
  { id: '24', rating: 4, description: 'Not great.', author_id: '7', game_id: '1' },
  { id: '25', rating: 8, description: 'Good game.', author_id: '1', game_id: '2' },
  { id: '26', rating: 5, description: 'Good game.', author_id: '2', game_id: '3' },
  { id: '27', rating: 10, description: 'Best game ever!', author_id: '3', game_id: '4' },
  { id: '28', rating: 8, description: 'Good story.', author_id: '4', game_id: '5' },
  { id: '29', rating: 9, description: 'Good controls.', author_id: '5', game_id: '6' },
  { id: '30', rating: 5, description: 'Good game.', author_id: '6', game_id: '7' },
  { id: '31', rating: 10, description: 'Best game of the year!', author_id: '7', game_id: '8' },
  { id: '32', rating: 8, description: 'Good graphics.', author_id: '1', game_id: '9' },
  { id: '33', rating: 5, description: 'Good game.', author_id: '2', game_id: '10' },
  { id: '34', rating: 10, description: 'Best game ever!', author_id: '3', game_id: '11' },
  { id: '35', rating: 8, description: 'Good game.', author_id: '4', game_id: '12' },
  { id: '36', rating: 9, description: 'Good story.', author_id: '5', game_id: '13' },
  { id: '37', rating: 5, description: 'Good game.', author_id: '6', game_id: '14' },
  { id: '38', rating: 10, description: 'Best multiplayer game!', author_id: '7', game_id: '15' },
  { id: '39', rating: 8, description: 'Good controls.', author_id: '1', game_id: '16' },
  { id: '40', rating: 5, description: 'Good game.', author_id: '2', game_id: '17' },
  { id: '41', rating: 10, description: 'Best game of the year!', author_id: '3', game_id: '18' },
  { id: '42', rating: 8, description: 'Good graphics.', author_id: '4', game_id: '19' },
  { id: '43', rating: 9, description: 'Good story.', author_id: '5', game_id: '20' },
  { id: '44', rating: 5, description: 'Good game.', author_id: '6', game_id: '1' },
  { id: '45', rating: 10, description: 'Best game ever!', author_id: '7', game_id: '2' },
  { id: '46', rating: 8, description: 'Good controls.', author_id: '1', game_id: '3' },
  { id: '47', rating: 5, description: 'Good game.', author_id: '2', game_id: '4' },
  { id: '48', rating: 10, description: 'Best multiplayer game!', author_id: '3', game_id: '5' },
  { id: '49', rating: 8, description: 'Good graphics.', author_id: '4', game_id: '6' },
  { id: '50', rating: 9, description: 'Good story.', author_id: '5', game_id: '7' },
]


export default { games, authors, reviews }